### ISSUE TITLE
im hungry

### ISSUE THREAD

**Issue by GabrielNaval** [DragonRagers/ADSB---Final-Project#3]
im hungry

**Comment by DragonRagers** [comment]
thats really too bad

**Comment by GabrielNaval** [comment]
Im still hungry tho

**Comment by Quelklef** [comment]
I suggest dedicated 50% of our budget to food. btw we broke

**Comment by Quelklef** [comment]
tru lol i agree

**Comment by Quelklef** [comment]
o shit dat me

**Comment by DragonRagers** [comment]
OK ELI IM COMING TO UR HOUSE FOR FOOD

**Comment by Quelklef** [comment]
no i dont have any snax im coming to ur house i want snax
