### ISSUE TITLE
Fix Player dependency on Polygon

### ISSUE THREAD

**Issue by DragonRagers** [DragonRagers/ADSB---Final-Project#8]
do it

**Comment by DragonRagers** [comment]
ill do it later

**Comment by Quelklef** [comment]
i'm hungry

**Comment by DragonRagers** [comment]
Actually we need it dependent on polygon

**Comment by Quelklef** [comment]
ugh i got some food earlier but now im hungry again but at the same time i feel kinda sick idk waht to do???
